#!/bin/sh
#
# Add records.

#set -x

default_endpoint=http://localhost:8080/jdnsaas/1.0/dns

url=$default_endpoint/views/internal/zones/zone.test/records

payload='{"records":[{"operation":"DELETE","name":"test1","timeToLive":86400,"type":"A","data":{"ipAddress":"172.16.0.201"}}]}'

echo $url

curl -i -s \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-X POST \
-d $payload \
$url

echo ""
exit 0
